-- 코드를 입력하세요
# SELECT CAR_ID,
# IF(
#     SUM(IF(START_DATE <= '2022-10-16' and END_DATE >= '2022-10-16', 1, 0)) > 0, 
#     '대여중', '대여 가능')
# AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC

# 세연님 코드
SELECT CAR_ID,
    MAX(CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중' ELSE '대여 가능' END) AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC 