-- 코드를 입력하세요
SELECT 
b.WRITER_ID, 
u.NICKNAME,
sum(b.PRICE) as TOTAL_SALES

from USED_GOODS_BOARD as b
join USED_GOODS_USER u on b.WRITER_ID = u.USER_ID

where STATUS = 'DONE'
Group by WRITER_ID
having TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;